[2023-11-15T13:03:09.451+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: peliculas_dag.task2 scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-15T13:03:09.563+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: peliculas_dag.task2 scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-15T13:03:09.682+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 6
[2023-11-15T13:03:09.990+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): task2> on 2023-11-09 00:00:00+00:00
[2023-11-15T13:03:10.178+0000] {standard_task_runner.py:57} INFO - Started process 170 to run task
[2023-11-15T13:03:10.222+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'peliculas_dag', 'task2', 'scheduled__2023-11-09T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/peliculas_dag.py', '--cfg-path', '/tmp/tmp9ak8bphr']
[2023-11-15T13:03:10.319+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask task2
[2023-11-15T13:03:11.144+0000] {task_command.py:410} INFO - Running <TaskInstance: peliculas_dag.task2 scheduled__2023-11-09T00:00:00+00:00 [running]> on host f8ec5917e7b3
[2023-11-15T13:03:12.455+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cristian' AIRFLOW_CTX_DAG_ID='peliculas_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-09T00:00:00+00:00'
[2023-11-15T13:03:13.409+0000] {logging_mixin.py:149} INFO - Error al obtener datos de la API o cargarlos en la base de datos: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2023-11-15T13:03:13.437+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-11-15T13:03:13.533+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=peliculas_dag, task_id=task2, execution_date=20231109T000000, start_date=20231115T130309, end_date=20231115T130313
[2023-11-15T13:03:13.641+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-11-15T13:03:13.762+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-15T17:45:48.081+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-09T00:00:00+00:00/task_id=task2 permission to 509
[2023-11-15T17:45:48.102+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-09T00:00:00+00:00/task_id=task2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-09T00:00:00+00:00/task_id=task2'
[2023-11-15T17:45:48.938+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-09T00:00:00+00:00/task_id=task2 permission to 509
[2023-11-15T17:45:48.952+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-09T00:00:00+00:00/task_id=task2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-09T00:00:00+00:00/task_id=task2'
[2023-11-15T17:45:49.512+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: peliculas_dag.task2 scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-15T17:45:49.740+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: peliculas_dag.task2 scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-15T17:45:49.754+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2023-11-15T17:45:50.176+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): task2> on 2023-11-09 00:00:00+00:00
[2023-11-15T17:45:50.284+0000] {standard_task_runner.py:57} INFO - Started process 126 to run task
[2023-11-15T17:45:50.319+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'peliculas_dag', 'task2', 'scheduled__2023-11-09T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/peliculas_dag.py', '--cfg-path', '/tmp/tmpjuwgxrwe']
[2023-11-15T17:45:50.352+0000] {standard_task_runner.py:85} INFO - Job 44: Subtask task2
[2023-11-15T17:45:50.803+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-09T00:00:00+00:00/task_id=task2 permission to 509
[2023-11-15T17:45:50.809+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-09T00:00:00+00:00/task_id=task2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-09T00:00:00+00:00/task_id=task2'
[2023-11-15T17:45:50.820+0000] {task_command.py:415} INFO - Running <TaskInstance: peliculas_dag.task2 scheduled__2023-11-09T00:00:00+00:00 [running]> on host 566b22168472
[2023-11-15T17:45:51.546+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cristian' AIRFLOW_CTX_DAG_ID='peliculas_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-09T00:00:00+00:00'
[2023-11-15T17:45:52.591+0000] {logging_mixin.py:151} INFO - Error al obtener datos de la API o cargarlos en la base de datos: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2023-11-15T17:45:52.608+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-15T17:45:52.683+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=peliculas_dag, task_id=task2, execution_date=20231109T000000, start_date=20231115T174549, end_date=20231115T174552
[2023-11-15T17:45:53.015+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-15T17:45:53.827+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
