[2023-11-15T13:02:44.626+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: peliculas_dag.task2 scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2023-11-15T13:02:45.348+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: peliculas_dag.task2 scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2023-11-15T13:02:45.430+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 6
[2023-11-15T13:02:48.159+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): task2> on 2023-11-06 00:00:00+00:00
[2023-11-15T13:02:48.265+0000] {standard_task_runner.py:57} INFO - Started process 168 to run task
[2023-11-15T13:02:48.436+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'peliculas_dag', 'task2', 'scheduled__2023-11-06T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/peliculas_dag.py', '--cfg-path', '/tmp/tmpnc5spq8m']
[2023-11-15T13:02:48.458+0000] {standard_task_runner.py:85} INFO - Job 23: Subtask task2
[2023-11-15T13:02:52.715+0000] {task_command.py:410} INFO - Running <TaskInstance: peliculas_dag.task2 scheduled__2023-11-06T00:00:00+00:00 [running]> on host f8ec5917e7b3
[2023-11-15T13:02:57.839+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cristian' AIRFLOW_CTX_DAG_ID='peliculas_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-11-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-06T00:00:00+00:00'
[2023-11-15T13:03:02.602+0000] {logging_mixin.py:149} INFO - Error al obtener datos de la API o cargarlos en la base de datos: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2023-11-15T13:03:02.651+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-11-15T13:03:03.013+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=peliculas_dag, task_id=task2, execution_date=20231106T000000, start_date=20231115T130244, end_date=20231115T130303
[2023-11-15T13:03:04.396+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-11-15T13:03:05.694+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-15T17:45:27.909+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-06T00:00:00+00:00/task_id=task2 permission to 509
[2023-11-15T17:45:28.004+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-06T00:00:00+00:00/task_id=task2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-06T00:00:00+00:00/task_id=task2'
[2023-11-15T17:45:29.055+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-06T00:00:00+00:00/task_id=task2 permission to 509
[2023-11-15T17:45:29.084+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-06T00:00:00+00:00/task_id=task2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-06T00:00:00+00:00/task_id=task2'
[2023-11-15T17:45:30.997+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: peliculas_dag.task2 scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2023-11-15T17:45:31.454+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: peliculas_dag.task2 scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2023-11-15T17:45:31.472+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2023-11-15T17:45:35.064+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): task2> on 2023-11-06 00:00:00+00:00
[2023-11-15T17:45:35.232+0000] {standard_task_runner.py:57} INFO - Started process 121 to run task
[2023-11-15T17:45:35.439+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'peliculas_dag', 'task2', 'scheduled__2023-11-06T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/peliculas_dag.py', '--cfg-path', '/tmp/tmprpj6qok4']
[2023-11-15T17:45:35.477+0000] {standard_task_runner.py:85} INFO - Job 41: Subtask task2
[2023-11-15T17:45:37.035+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-06T00:00:00+00:00/task_id=task2 permission to 509
[2023-11-15T17:45:37.043+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-06T00:00:00+00:00/task_id=task2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-06T00:00:00+00:00/task_id=task2'
[2023-11-15T17:45:37.324+0000] {task_command.py:415} INFO - Running <TaskInstance: peliculas_dag.task2 scheduled__2023-11-06T00:00:00+00:00 [running]> on host 566b22168472
[2023-11-15T17:45:40.999+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cristian' AIRFLOW_CTX_DAG_ID='peliculas_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-11-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-06T00:00:00+00:00'
[2023-11-15T17:45:43.700+0000] {logging_mixin.py:151} INFO - Error al obtener datos de la API o cargarlos en la base de datos: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2023-11-15T17:45:43.777+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-15T17:45:43.901+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=peliculas_dag, task_id=task2, execution_date=20231106T000000, start_date=20231115T174531, end_date=20231115T174543
[2023-11-15T17:45:44.474+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-15T17:45:46.948+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
