[2023-11-15T13:03:12.484+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: peliculas_dag.task2 scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-15T13:03:12.638+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: peliculas_dag.task2 scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-15T13:03:12.648+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 6
[2023-11-15T13:03:12.884+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): task2> on 2023-11-12 00:00:00+00:00
[2023-11-15T13:03:12.917+0000] {standard_task_runner.py:57} INFO - Started process 180 to run task
[2023-11-15T13:03:12.955+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'peliculas_dag', 'task2', 'scheduled__2023-11-12T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/peliculas_dag.py', '--cfg-path', '/tmp/tmp0ptwcwsu']
[2023-11-15T13:03:12.986+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask task2
[2023-11-15T13:03:13.435+0000] {task_command.py:410} INFO - Running <TaskInstance: peliculas_dag.task2 scheduled__2023-11-12T00:00:00+00:00 [running]> on host f8ec5917e7b3
[2023-11-15T13:03:14.042+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cristian' AIRFLOW_CTX_DAG_ID='peliculas_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-11-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-12T00:00:00+00:00'
[2023-11-15T13:03:14.887+0000] {logging_mixin.py:149} INFO - Error al obtener datos de la API o cargarlos en la base de datos: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2023-11-15T13:03:14.888+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-11-15T13:03:14.916+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=peliculas_dag, task_id=task2, execution_date=20231112T000000, start_date=20231115T130312, end_date=20231115T130314
[2023-11-15T13:03:14.991+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-11-15T13:03:15.027+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-15T17:45:34.757+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-12T00:00:00+00:00/task_id=task2 permission to 509
[2023-11-15T17:45:34.769+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-12T00:00:00+00:00/task_id=task2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-12T00:00:00+00:00/task_id=task2'
[2023-11-15T17:45:35.610+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-12T00:00:00+00:00/task_id=task2 permission to 509
[2023-11-15T17:45:35.627+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-12T00:00:00+00:00/task_id=task2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-12T00:00:00+00:00/task_id=task2'
[2023-11-15T17:45:36.507+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: peliculas_dag.task2 scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-15T17:45:36.826+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: peliculas_dag.task2 scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-15T17:45:36.844+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2023-11-15T17:45:38.586+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): task2> on 2023-11-12 00:00:00+00:00
[2023-11-15T17:45:38.995+0000] {standard_task_runner.py:57} INFO - Started process 123 to run task
[2023-11-15T17:45:39.120+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'peliculas_dag', 'task2', 'scheduled__2023-11-12T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/peliculas_dag.py', '--cfg-path', '/tmp/tmp188fk6pn']
[2023-11-15T17:45:39.194+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask task2
[2023-11-15T17:45:40.937+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-12T00:00:00+00:00/task_id=task2 permission to 509
[2023-11-15T17:45:40.951+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-12T00:00:00+00:00/task_id=task2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-12T00:00:00+00:00/task_id=task2'
[2023-11-15T17:45:41.071+0000] {task_command.py:415} INFO - Running <TaskInstance: peliculas_dag.task2 scheduled__2023-11-12T00:00:00+00:00 [running]> on host 566b22168472
[2023-11-15T17:45:43.226+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cristian' AIRFLOW_CTX_DAG_ID='peliculas_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-11-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-12T00:00:00+00:00'
[2023-11-15T17:45:45.434+0000] {logging_mixin.py:151} INFO - Error al obtener datos de la API o cargarlos en la base de datos: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2023-11-15T17:45:45.488+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-15T17:45:45.911+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=peliculas_dag, task_id=task2, execution_date=20231112T000000, start_date=20231115T174536, end_date=20231115T174545
[2023-11-15T17:45:47.009+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-15T17:45:47.527+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
