[2023-11-15T13:02:38.210+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: peliculas_dag.task2 scheduled__2023-11-04T00:00:00+00:00 [queued]>
[2023-11-15T13:02:38.396+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: peliculas_dag.task2 scheduled__2023-11-04T00:00:00+00:00 [queued]>
[2023-11-15T13:02:38.415+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 6
[2023-11-15T13:02:38.821+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): task2> on 2023-11-04 00:00:00+00:00
[2023-11-15T13:02:38.875+0000] {standard_task_runner.py:57} INFO - Started process 162 to run task
[2023-11-15T13:02:38.943+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'peliculas_dag', 'task2', 'scheduled__2023-11-04T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/peliculas_dag.py', '--cfg-path', '/tmp/tmphqfbxm2d']
[2023-11-15T13:02:38.948+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask task2
[2023-11-15T13:02:40.174+0000] {task_command.py:410} INFO - Running <TaskInstance: peliculas_dag.task2 scheduled__2023-11-04T00:00:00+00:00 [running]> on host f8ec5917e7b3
[2023-11-15T13:02:44.352+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cristian' AIRFLOW_CTX_DAG_ID='peliculas_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-11-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-04T00:00:00+00:00'
[2023-11-15T13:02:48.727+0000] {logging_mixin.py:149} INFO - Error al obtener datos de la API o cargarlos en la base de datos: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2023-11-15T13:02:48.732+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-11-15T13:02:49.088+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=peliculas_dag, task_id=task2, execution_date=20231104T000000, start_date=20231115T130238, end_date=20231115T130249
[2023-11-15T13:02:54.237+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-11-15T13:02:55.560+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-15T17:45:17.184+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-04T00:00:00+00:00/task_id=task2 permission to 509
[2023-11-15T17:45:17.261+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-04T00:00:00+00:00/task_id=task2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-04T00:00:00+00:00/task_id=task2'
[2023-11-15T17:45:18.839+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-04T00:00:00+00:00/task_id=task2 permission to 509
[2023-11-15T17:45:18.857+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-04T00:00:00+00:00/task_id=task2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-04T00:00:00+00:00/task_id=task2'
[2023-11-15T17:45:23.145+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: peliculas_dag.task2 scheduled__2023-11-04T00:00:00+00:00 [queued]>
[2023-11-15T17:45:23.379+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: peliculas_dag.task2 scheduled__2023-11-04T00:00:00+00:00 [queued]>
[2023-11-15T17:45:23.382+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2023-11-15T17:45:24.309+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): task2> on 2023-11-04 00:00:00+00:00
[2023-11-15T17:45:24.553+0000] {standard_task_runner.py:57} INFO - Started process 112 to run task
[2023-11-15T17:45:24.902+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'peliculas_dag', 'task2', 'scheduled__2023-11-04T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/peliculas_dag.py', '--cfg-path', '/tmp/tmptnqmuumy']
[2023-11-15T17:45:24.964+0000] {standard_task_runner.py:85} INFO - Job 39: Subtask task2
[2023-11-15T17:45:26.137+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-04T00:00:00+00:00/task_id=task2 permission to 509
[2023-11-15T17:45:26.200+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-04T00:00:00+00:00/task_id=task2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-04T00:00:00+00:00/task_id=task2'
[2023-11-15T17:45:26.284+0000] {task_command.py:415} INFO - Running <TaskInstance: peliculas_dag.task2 scheduled__2023-11-04T00:00:00+00:00 [running]> on host 566b22168472
[2023-11-15T17:45:29.950+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cristian' AIRFLOW_CTX_DAG_ID='peliculas_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-11-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-04T00:00:00+00:00'
[2023-11-15T17:45:31.923+0000] {logging_mixin.py:151} INFO - Error al obtener datos de la API o cargarlos en la base de datos: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2023-11-15T17:45:32.005+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-15T17:45:32.400+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=peliculas_dag, task_id=task2, execution_date=20231104T000000, start_date=20231115T174523, end_date=20231115T174532
[2023-11-15T17:45:35.449+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-15T17:45:35.730+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
