[2023-11-15T13:02:43.495+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: peliculas_dag.task2 scheduled__2023-11-03T00:00:00+00:00 [queued]>
[2023-11-15T13:02:44.781+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: peliculas_dag.task2 scheduled__2023-11-03T00:00:00+00:00 [queued]>
[2023-11-15T13:02:44.861+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 6
[2023-11-15T13:02:46.618+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): task2> on 2023-11-03 00:00:00+00:00
[2023-11-15T13:02:46.914+0000] {standard_task_runner.py:57} INFO - Started process 167 to run task
[2023-11-15T13:02:47.264+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'peliculas_dag', 'task2', 'scheduled__2023-11-03T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/peliculas_dag.py', '--cfg-path', '/tmp/tmpqshp43wv']
[2023-11-15T13:02:47.333+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask task2
[2023-11-15T13:02:52.351+0000] {task_command.py:410} INFO - Running <TaskInstance: peliculas_dag.task2 scheduled__2023-11-03T00:00:00+00:00 [running]> on host f8ec5917e7b3
[2023-11-15T13:02:58.856+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cristian' AIRFLOW_CTX_DAG_ID='peliculas_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-11-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-03T00:00:00+00:00'
[2023-11-15T13:03:02.579+0000] {logging_mixin.py:149} INFO - Error al obtener datos de la API o cargarlos en la base de datos: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2023-11-15T13:03:02.619+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-11-15T13:03:03.064+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=peliculas_dag, task_id=task2, execution_date=20231103T000000, start_date=20231115T130243, end_date=20231115T130303
[2023-11-15T13:03:04.398+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-11-15T13:03:05.665+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-15T17:45:27.219+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-03T00:00:00+00:00/task_id=task2 permission to 509
[2023-11-15T17:45:27.265+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-03T00:00:00+00:00/task_id=task2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-03T00:00:00+00:00/task_id=task2'
[2023-11-15T17:45:28.580+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-03T00:00:00+00:00/task_id=task2 permission to 509
[2023-11-15T17:45:28.591+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-03T00:00:00+00:00/task_id=task2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-03T00:00:00+00:00/task_id=task2'
[2023-11-15T17:45:29.672+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: peliculas_dag.task2 scheduled__2023-11-03T00:00:00+00:00 [queued]>
[2023-11-15T17:45:29.988+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: peliculas_dag.task2 scheduled__2023-11-03T00:00:00+00:00 [queued]>
[2023-11-15T17:45:30.003+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2023-11-15T17:45:30.679+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): task2> on 2023-11-03 00:00:00+00:00
[2023-11-15T17:45:30.830+0000] {standard_task_runner.py:57} INFO - Started process 114 to run task
[2023-11-15T17:45:31.198+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'peliculas_dag', 'task2', 'scheduled__2023-11-03T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/peliculas_dag.py', '--cfg-path', '/tmp/tmp24cjbcva']
[2023-11-15T17:45:31.237+0000] {standard_task_runner.py:85} INFO - Job 40: Subtask task2
[2023-11-15T17:45:32.794+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-03T00:00:00+00:00/task_id=task2 permission to 509
[2023-11-15T17:45:32.805+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-03T00:00:00+00:00/task_id=task2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-03T00:00:00+00:00/task_id=task2'
[2023-11-15T17:45:32.840+0000] {task_command.py:415} INFO - Running <TaskInstance: peliculas_dag.task2 scheduled__2023-11-03T00:00:00+00:00 [running]> on host 566b22168472
[2023-11-15T17:45:34.899+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cristian' AIRFLOW_CTX_DAG_ID='peliculas_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2023-11-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-03T00:00:00+00:00'
[2023-11-15T17:45:37.131+0000] {logging_mixin.py:151} INFO - Error al obtener datos de la API o cargarlos en la base de datos: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2023-11-15T17:45:37.213+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-15T17:45:38.309+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=peliculas_dag, task_id=task2, execution_date=20231103T000000, start_date=20231115T174529, end_date=20231115T174538
[2023-11-15T17:45:39.099+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-15T17:45:40.295+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
