[2023-11-15T14:49:52.273+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: peliculas_dag.send_email_alert manual__2023-11-15T14:49:41.225073+00:00 [queued]>
[2023-11-15T14:49:52.287+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: peliculas_dag.send_email_alert manual__2023-11-15T14:49:41.225073+00:00 [queued]>
[2023-11-15T14:49:52.288+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 6
[2023-11-15T14:49:52.319+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): send_email_alert> on 2023-11-15 14:49:41.225073+00:00
[2023-11-15T14:49:52.325+0000] {standard_task_runner.py:57} INFO - Started process 145 to run task
[2023-11-15T14:49:52.330+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'peliculas_dag', 'send_email_alert', 'manual__2023-11-15T14:49:41.225073+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/peliculas_dag.py', '--cfg-path', '/tmp/tmprquw5o17']
[2023-11-15T14:49:52.331+0000] {standard_task_runner.py:85} INFO - Job 155: Subtask send_email_alert
[2023-11-15T14:49:52.416+0000] {task_command.py:410} INFO - Running <TaskInstance: peliculas_dag.send_email_alert manual__2023-11-15T14:49:41.225073+00:00 [running]> on host b604b9149076
[2023-11-15T14:49:52.519+0000] {abstractoperator.py:582} ERROR - Exception rendering Jinja template for task 'send_email_alert', field 'op_args'. Template: ['Alerta de peliculas Recientes', '', ['cristiancorrea85@gmail.com'], "{{ ti.xcom_pull(task_ids='task2')[0] }}"]
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 574, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 166, in render_template
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 166, in <listcomp>
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 539, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: None has no element 0
[2023-11-15T14:49:52.521+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1430, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1554, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2202, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 574, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 166, in render_template
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 166, in <listcomp>
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 539, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: None has no element 0
[2023-11-15T14:49:52.534+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=peliculas_dag, task_id=send_email_alert, execution_date=20231115T144941, start_date=20231115T144952, end_date=20231115T144952
[2023-11-15T14:49:52.550+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 155 for task send_email_alert (None has no element 0; 145)
[2023-11-15T14:49:52.582+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-11-15T14:49:52.661+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
